#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Parledoct  # The title of the book. Will be placed in the left navbar.
author                      : <a href="https://resunay.com">Nay San</a>  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

sphinx:
  config:
    html_theme_options:
      show_navbar_depth: 2

# Information about where the book exists on the web
repository:
  url: https://github.com/parledoct/Parledoct  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
